import type { Property, PropertyType, PlaceType } from "./types";

export const DEFAULT_PRICE_MIN = 50;
export const DEFAULT_PRICE_MAX = 1500;
export const DEFAULT_PER_PAGE = 9;

export { GUEST_OPTIONS } from "@/components/common/search";

// Location search uses shared SearchPanel (worldwide autocomplete)

export const SORT_OPTIONS = [
  { value: "latest", label: "Latest" },
  { value: "price-asc", label: "Price: Low to High" },
  { value: "price-desc", label: "Price: High to Low" },
  { value: "rating", label: "Top Rated" },
] as const;

export const CATEGORIES = [
  { id: "all", label: "All", icon: "layout-grid" },
  { id: "cabin", label: "Cabin", icon: "home" },
  { id: "countryside", label: "Country Side", icon: "trees" },
  { id: "tiny-homes", label: "Tiny Homes", icon: "box" },
  { id: "farm-houses", label: "Farm Houses", icon: "warehouse" },
  { id: "camping", label: "Camping", icon: "tent" },
  { id: "iconic-cities", label: "Iconic Cities", icon: "building-2" },
  { id: "lake-front", label: "Lake Front", icon: "waves" },
] as const;

export const PLACE_TYPE_OPTIONS: { value: PlaceType; label: string; description: string }[] = [
  { value: "entire", label: "Entire place", description: "Have the whole place to yourself" },
  { value: "shared", label: "Shared room", description: "Stay in a shared space, like a common room" },
  { value: "room", label: "Room", description: "Have your own room and share some common spaces" },
];

export const PROPERTY_TYPE_OPTIONS: { value: PropertyType; label: string }[] = [
  { value: "house", label: "House" },
  { value: "apartment", label: "Apartment" },
  { value: "cabin", label: "Cabin" },
  { value: "villa", label: "Villa" },
  { value: "camping", label: "Camping" },
];

export const COUNT_OPTIONS = ["any", "1", "2", "3", "4", "5+"] as const;

const img = (id: string) =>
  `https://images.unsplash.com/${id}?w=800&h=600&fit=crop`;

export const MOCK_PROPERTIES: Property[] = [
  {
    id: "1",
    title: "Beautiful Malibu Mansion",
    address: "1142 Malibu Point, Malibu, CA 90165",
    city: "Malibu",
    country: "USA",
    image: img("photo-1613490493576-7fde63acd811"),
    rating: 4.8,
    bedrooms: 3,
    beds: 3,
    bathrooms: 1,
    pricePerNight: 620,
    category: "lake-front",
    placeType: "entire",
    propertyType: "villa",
    createdAt: "2026-01-15",
  },
  {
    id: "2",
    title: "A Cabin in Lost River",
    address: "Lost River, West Virginia",
    city: "Lost River",
    country: "USA",
    image: img("photo-1449824913935-59a10b8d2001"),
    rating: 4.8,
    bedrooms: 3,
    beds: 3,
    bathrooms: 2,
    pricePerNight: 215,
    category: "cabin",
    placeType: "entire",
    propertyType: "cabin",
    createdAt: "2026-01-10",
  },
  {
    id: "3",
    title: "A Cabin in Lost River",
    address: "Lost River, West Virginia",
    city: "Lost River",
    country: "USA",
    image: img("photo-1518780669437-660660209564"),
    rating: 4.7,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    pricePerNight: 195,
    category: "cabin",
    placeType: "room",
    propertyType: "cabin",
    createdAt: "2026-01-08",
  },
  {
    id: "4",
    title: "A Cabin in Lost River",
    address: "Lost River, West Virginia",
    city: "Lost River",
    country: "USA",
    image: img("photo-1502672260266-1c1ef2e93688"),
    rating: 4.9,
    bedrooms: 4,
    beds: 4,
    bathrooms: 2,
    pricePerNight: 240,
    category: "countryside",
    placeType: "entire",
    propertyType: "house",
    createdAt: "2026-01-05",
  },
  {
    id: "5",
    title: "A Cabin in Lost River",
    address: "Lost River, West Virginia",
    city: "Lost River",
    country: "USA",
    image: img("photo-1564013799919-ab600027ffc6"),
    rating: 4.6,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    pricePerNight: 120,
    category: "tiny-homes",
    placeType: "entire",
    propertyType: "house",
    createdAt: "2026-01-02",
  },
  {
    id: "6",
    title: "A Cabin in Lost River",
    address: "Lost River, West Virginia",
    city: "Lost River",
    country: "USA",
    image: img("photo-1582268611958-ebfd161ef9cf"),
    rating: 4.8,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    pricePerNight: 210,
    category: "farm-houses",
    placeType: "entire",
    propertyType: "house",
    createdAt: "2025-12-28",
  },
  {
    id: "7",
    title: "Lakeside Toronto Retreat",
    address: "42 Harbour St, Toronto, ON",
    city: "Toronto",
    country: "Canada",
    image: img("photo-1522708323590-d24dbb6b0267"),
    rating: 4.9,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    pricePerNight: 185,
    category: "iconic-cities",
    placeType: "entire",
    propertyType: "apartment",
    createdAt: "2026-01-20",
  },
  {
    id: "8",
    title: "Downtown Toronto Loft",
    address: "88 Queen St W, Toronto, ON",
    city: "Toronto",
    country: "Canada",
    image: img("photo-1493809842364-78817add7ffb"),
    rating: 4.7,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    pricePerNight: 145,
    category: "iconic-cities",
    placeType: "room",
    propertyType: "apartment",
    createdAt: "2026-01-18",
  },
  {
    id: "9",
    title: "Swiss Alpine Chalet",
    address: "Zermatt, Valais",
    city: "Zermatt",
    country: "Switzerland",
    image: img("photo-1512917774080-9991f1c4c750"),
    rating: 4.9,
    bedrooms: 4,
    beds: 5,
    bathrooms: 3,
    pricePerNight: 380,
    category: "cabin",
    placeType: "entire",
    propertyType: "cabin",
    createdAt: "2026-01-12",
  },
  {
    id: "10",
    title: "Geneva Lake House",
    address: "Quai du Mont-Blanc, Geneva",
    city: "Geneva",
    country: "Switzerland",
    image: img("photo-1600596542815-ffad4c1539a9"),
    rating: 4.8,
    bedrooms: 3,
    beds: 3,
    bathrooms: 2,
    pricePerNight: 290,
    category: "lake-front",
    placeType: "entire",
    propertyType: "house",
    createdAt: "2026-01-11",
  },
  {
    id: "11",
    title: "Paris Iconic Apartment",
    address: "12 Rue de Rivoli, Paris",
    city: "Paris",
    country: "France",
    image: img("photo-1502672260266-1c1ef2e93688"),
    rating: 4.6,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    pricePerNight: 220,
    category: "iconic-cities",
    placeType: "entire",
    propertyType: "apartment",
    createdAt: "2026-01-09",
  },
  {
    id: "12",
    title: "Countryside Farm Stay",
    address: "Provence, France",
    city: "Provence",
    country: "France",
    image: img("photo-1600585154340-be6161a56a0c"),
    rating: 4.7,
    bedrooms: 5,
    beds: 6,
    bathrooms: 3,
    pricePerNight: 175,
    category: "farm-houses",
    placeType: "entire",
    propertyType: "house",
    createdAt: "2026-01-07",
  },
  {
    id: "13",
    title: "Tiny Home in the Woods",
    address: "Asheville, North Carolina",
    city: "Asheville",
    country: "USA",
    image: img("photo-1600047509800-ba8f99d2cdde"),
    rating: 4.8,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    pricePerNight: 95,
    category: "tiny-homes",
    placeType: "entire",
    propertyType: "house",
    createdAt: "2026-01-06",
  },
  {
    id: "14",
    title: "Camping Under the Stars",
    address: "Banff National Park, Canada",
    city: "Banff",
    country: "Canada",
    image: img("photo-1478136340534-42aae010f6a0"),
    rating: 4.5,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    pricePerNight: 65,
    category: "camping",
    placeType: "shared",
    propertyType: "camping",
    createdAt: "2026-01-04",
  },
  {
    id: "15",
    title: "Tokyo Modern Stay",
    address: "Shibuya, Tokyo",
    city: "Tokyo",
    country: "Japan",
    image: img("photo-1522708323590-d24dbb6b0267"),
    rating: 4.9,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    pricePerNight: 160,
    category: "iconic-cities",
    placeType: "room",
    propertyType: "apartment",
    createdAt: "2026-01-22",
  },
  {
    id: "16",
    title: "Lakefront Cottage",
    address: "Muskoka, Ontario",
    city: "Muskoka",
    country: "Canada",
    image: img("photo-1605276374104-dee2a0ed3cd6"),
    rating: 4.8,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    pricePerNight: 230,
    category: "lake-front",
    placeType: "entire",
    propertyType: "cabin",
    createdAt: "2026-01-14",
  },
  {
    id: "17",
    title: "Rustic Country Cabin",
    address: "Blue Ridge, Georgia",
    city: "Blue Ridge",
    country: "USA",
    image: img("photo-1449158743715-0a90ebb6d2d8"),
    rating: 4.7,
    bedrooms: 2,
    beds: 3,
    bathrooms: 1,
    pricePerNight: 140,
    category: "countryside",
    placeType: "entire",
    propertyType: "cabin",
    createdAt: "2026-01-03",
  },
  {
    id: "18",
    title: "Farmhouse with Pasture Views",
    address: "Lancaster, Pennsylvania",
    city: "Lancaster",
    country: "USA",
    image: img("photo-1568605114967-8130f5a36994"),
    rating: 4.6,
    bedrooms: 4,
    beds: 5,
    bathrooms: 2,
    pricePerNight: 155,
    category: "farm-houses",
    placeType: "entire",
    propertyType: "house",
    createdAt: "2025-12-30",
  },
  {
    id: "19",
    title: "Compact Urban Tiny Home",
    address: "Portland, Oregon",
    city: "Portland",
    country: "USA",
    image: img("photo-1600585154526-990dced4db0d"),
    rating: 4.5,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    pricePerNight: 88,
    category: "tiny-homes",
    placeType: "entire",
    propertyType: "house",
    createdAt: "2025-12-25",
  },
  {
    id: "20",
    title: "Glamping Tent Experience",
    address: "Yosemite, California",
    city: "Yosemite",
    country: "USA",
    image: img("photo-1478136340534-42aae010f6a0"),
    rating: 4.4,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    pricePerNight: 72,
    category: "camping",
    placeType: "shared",
    propertyType: "camping",
    createdAt: "2025-12-20",
  },
  {
    id: "21",
    title: "Toronto Family Home",
    address: "55 Bloor St E, Toronto, ON",
    city: "Toronto",
    country: "Canada",
    image: img("photo-1600607687939-ce8a6c25118c"),
    rating: 4.8,
    bedrooms: 3,
    beds: 3,
    bathrooms: 2,
    pricePerNight: 200,
    category: "iconic-cities",
    placeType: "entire",
    propertyType: "house",
    createdAt: "2026-01-19",
  },
  {
    id: "22",
    title: "Swiss Countryside Villa",
    address: "Interlaken, Switzerland",
    city: "Interlaken",
    country: "Switzerland",
    image: img("photo-1600585154340-be6161a56a0c"),
    rating: 4.9,
    bedrooms: 5,
    beds: 6,
    bathrooms: 4,
    pricePerNight: 450,
    category: "countryside",
    placeType: "entire",
    propertyType: "villa",
    createdAt: "2026-01-16",
  },
  {
    id: "23",
    title: "Malibu Beach House",
    address: "21056 Pacific Coast Hwy, Malibu",
    city: "Malibu",
    country: "USA",
    image: img("photo-1600047509358-9dc75507daeb"),
    rating: 4.9,
    bedrooms: 4,
    beds: 4,
    bathrooms: 3,
    pricePerNight: 580,
    category: "lake-front",
    placeType: "entire",
    propertyType: "villa",
    createdAt: "2026-01-17",
  },
  {
    id: "24",
    title: "Cozy Toronto Cabin",
    address: "Toronto Islands, ON",
    city: "Toronto",
    country: "Canada",
    image: img("photo-1518780669437-660660209564"),
    rating: 4.7,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    pricePerNight: 170,
    category: "cabin",
    placeType: "room",
    propertyType: "cabin",
    createdAt: "2026-01-13",
  },
];
