import { getWholesaleGuestPriceUsdRounded } from "@/lib/currency/format";
import { getTimezoneForCity } from "@/lib/booking/timezone";
import type { Property } from "./types";

type PropertySeed = Omit<Property, "timezone">;

const img = (id: string) =>
  `https://images.unsplash.com/${id}?w=800&h=600&fit=crop`;

const RAW_PROPERTIES: PropertySeed[] = [
  {
    id: "1",
    title: "RestHalf Airport Transit Hotel",
    address: "Near Kempegowda Intl Airport, Bangalore",
    city: "Bangalore",
    country: "India",
    image: img("photo-1566073771259-6a8506099945"),
    rating: 4.8,
    starRating: 4,
    lane: "direct",
    priceUsd: 22,
    priceIdr: 350000,
    roomType: "double",
    maxOccupancy: 2,
    amenities: ["WiFi", "AC", "Airport shuttle"],
    category: "near-airport",
    distanceFromAirportKm: 2.1,
    slotDuration: "12h",
    ringFencedRooms: 8,
    nextAvailableSlot: "12:00 today",
    createdAt: "2026-01-20",
  },
  {
    id: "2",
    title: "Skyline Business Hotel",
    address: "MG Road, Bangalore",
    city: "Bangalore",
    country: "India",
    image: img("photo-1551882547-ff40c63fe5fa"),
    rating: 4.6,
    starRating: 4,
    lane: "wholesale",
    priceUsd: 85,
    priceIdr: 0,
    roomType: "double",
    maxOccupancy: 2,
    amenities: ["WiFi", "AC", "Gym", "Breakfast"],
    category: "business",
    distanceFromAirportKm: 28,
    slotDuration: "24h",
    supplierName: "Hotelbeds",
    wholesalePricing: { supplierBaseAmount: 72, supplierCurrency: "EUR", markupRate: 0.12 },
    createdAt: "2026-01-18",
  },
  {
    id: "3",
    title: "Layover Lounge Suites",
    address: "Heathrow Airport Zone, London",
    city: "London",
    country: "United Kingdom",
    image: img("photo-1611892440507-8b5067397e1a"),
    rating: 4.9,
    starRating: 5,
    lane: "direct",
    priceUsd: 45,
    priceIdr: 720000,
    roomType: "suite",
    maxOccupancy: 2,
    amenities: ["WiFi", "AC", "Airport shuttle", "Breakfast"],
    category: "layover-friendly",
    distanceFromAirportKm: 1.5,
    slotDuration: "12h",
    ringFencedRooms: 5,
    nextAvailableSlot: "00:00 tomorrow",
    createdAt: "2026-01-19",
  },
  {
    id: "4",
    title: "City Center Grand",
    address: "Downtown Toronto, ON",
    city: "Toronto",
    country: "Canada",
    image: img("photo-1522708323590-d24dbb6b0267"),
    rating: 4.7,
    starRating: 4,
    lane: "wholesale",
    priceUsd: 120,
    priceIdr: 0,
    roomType: "double",
    maxOccupancy: 3,
    amenities: ["WiFi", "AC", "Pool", "Gym"],
    category: "city-center",
    distanceFromAirportKm: 22,
    slotDuration: "24h",
    supplierName: "Expedia Partner",
    wholesalePricing: { supplierBaseAmount: 105, supplierCurrency: "USD", markupRate: 0.1 },
    createdAt: "2026-01-17",
  },
  {
    id: "5",
    title: "RestHalf Express Changi",
    address: "Near Changi Airport, Singapore",
    city: "Singapore",
    country: "Singapore",
    image: img("photo-1571896349847-33c89424de2d"),
    rating: 4.8,
    starRating: 3,
    lane: "direct",
    priceUsd: 38,
    priceIdr: 600000,
    roomType: "single",
    maxOccupancy: 1,
    amenities: ["WiFi", "AC", "Airport shuttle"],
    category: "near-airport",
    distanceFromAirportKm: 3.2,
    slotDuration: "12h",
    ringFencedRooms: 12,
    nextAvailableSlot: "12:00 today",
    createdAt: "2026-01-16",
  },
  {
    id: "6",
    title: "Marina Bay Partner Hotel",
    address: "Marina Bay, Singapore",
    city: "Singapore",
    country: "Singapore",
    image: img("photo-1582719478250-c89cae4dc85b"),
    rating: 4.5,
    starRating: 5,
    lane: "wholesale",
    priceUsd: 210,
    priceIdr: 0,
    roomType: "suite",
    maxOccupancy: 2,
    amenities: ["WiFi", "AC", "Pool", "Breakfast", "Gym"],
    category: "city-center",
    distanceFromAirportKm: 18,
    slotDuration: "24h",
    supplierName: "Booking.com Supply",
    wholesalePricing: { supplierBaseAmount: 155, supplierCurrency: "GBP", markupRate: 0.15 },
    createdAt: "2026-01-15",
  },
  {
    id: "7",
    title: "Dubai Transit Rest Pod",
    address: "DXB Airport Corridor, Dubai",
    city: "Dubai",
    country: "UAE",
    image: img("photo-1512917774080-9991f1c4c750"),
    rating: 4.7,
    starRating: 4,
    lane: "direct",
    priceUsd: 55,
    priceIdr: 870000,
    roomType: "double",
    maxOccupancy: 2,
    amenities: ["WiFi", "AC", "Airport shuttle"],
    category: "layover-friendly",
    distanceFromAirportKm: 0.8,
    slotDuration: "24h",
    ringFencedRooms: 6,
    nextAvailableSlot: "00:00 today",
    createdAt: "2026-01-14",
  },
  {
    id: "8",
    title: "Paris Central Stay",
    address: "Rue de Rivoli, Paris",
    city: "Paris",
    country: "France",
    image: img("photo-1502672260266-1c1ef2e93688"),
    rating: 4.6,
    starRating: 4,
    lane: "wholesale",
    priceUsd: 165,
    priceIdr: 0,
    roomType: "double",
    maxOccupancy: 2,
    amenities: ["WiFi", "AC", "Breakfast"],
    category: "city-center",
    distanceFromAirportKm: 25,
    slotDuration: "24h",
    supplierName: "Restel",
    wholesalePricing: { supplierBaseAmount: 140, supplierCurrency: "EUR", markupRate: 0.12 },
    createdAt: "2026-01-13",
  },
  {
    id: "9",
    title: "Tokyo Haneda RestHalf",
    address: "Haneda Airport Area, Tokyo",
    city: "Tokyo",
    country: "Japan",
    image: img("photo-1520250497590-112bad2d2042"),
    rating: 4.9,
    starRating: 4,
    lane: "direct",
    priceUsd: 42,
    priceIdr: 665000,
    roomType: "single",
    maxOccupancy: 1,
    amenities: ["WiFi", "AC", "Airport shuttle"],
    category: "near-airport",
    distanceFromAirportKm: 1.2,
    slotDuration: "12h",
    ringFencedRooms: 10,
    nextAvailableSlot: "12:00 today",
    createdAt: "2026-01-12",
  },
  {
    id: "10",
    title: "Shibuya Partner Inn",
    address: "Shibuya, Tokyo",
    city: "Tokyo",
    country: "Japan",
    image: img("photo-1566665797739-1674afdd4fcb"),
    rating: 4.4,
    starRating: 3,
    lane: "wholesale",
    priceUsd: 95,
    priceIdr: 0,
    roomType: "double",
    maxOccupancy: 2,
    amenities: ["WiFi", "AC"],
    category: "city-center",
    distanceFromAirportKm: 30,
    slotDuration: "24h",
    supplierName: "Agoda Wholesale",
    wholesalePricing: { supplierBaseAmount: 82, supplierCurrency: "USD", markupRate: 0.11 },
    createdAt: "2026-01-11",
  },
  {
    id: "11",
    title: "JFK Layover Suites",
    address: "JFK Airport Zone, New York",
    city: "New York",
    country: "USA",
    image: img("photo-1613490493576-7fde63acd811"),
    rating: 4.5,
    starRating: 4,
    lane: "direct",
    priceUsd: 65,
    priceIdr: 1025000,
    roomType: "suite",
    maxOccupancy: 2,
    amenities: ["WiFi", "AC", "Airport shuttle", "Breakfast"],
    category: "layover-friendly",
    distanceFromAirportKm: 2.5,
    slotDuration: "12h",
    ringFencedRooms: 4,
    nextAvailableSlot: "00:00 tomorrow",
    createdAt: "2026-01-10",
  },
  {
    id: "12",
    title: "Manhattan Wholesale Tower",
    address: "Midtown Manhattan, New York",
    city: "New York",
    country: "USA",
    image: img("photo-1600607687939-ce8a6c25118c"),
    rating: 4.7,
    starRating: 5,
    lane: "wholesale",
    priceUsd: 245,
    priceIdr: 0,
    roomType: "suite",
    maxOccupancy: 3,
    amenities: ["WiFi", "AC", "Pool", "Gym", "Breakfast"],
    category: "business",
    distanceFromAirportKm: 35,
    slotDuration: "24h",
    supplierName: "Hotelbeds",
    wholesalePricing: { supplierBaseAmount: 215, supplierCurrency: "USD", markupRate: 0.14 },
    createdAt: "2026-01-09",
  },
  {
    id: "13",
    title: "Zurich Airport RestHalf",
    address: "Kloten, Zurich",
    city: "Zurich",
    country: "Switzerland",
    image: img("photo-1600047509358-9dc75507daeb"),
    rating: 4.8,
    starRating: 4,
    lane: "direct",
    priceUsd: 58,
    priceIdr: 920000,
    roomType: "double",
    maxOccupancy: 2,
    amenities: ["WiFi", "AC", "Airport shuttle"],
    category: "near-airport",
    distanceFromAirportKm: 1.8,
    slotDuration: "12h",
    ringFencedRooms: 7,
    nextAvailableSlot: "12:00 today",
    createdAt: "2026-01-08",
  },
  {
    id: "14",
    title: "Alpine Partner Lodge",
    address: "Interlaken, Switzerland",
    city: "Interlaken",
    country: "Switzerland",
    image: img("photo-1600585154340-be6161a56a0c"),
    rating: 4.6,
    starRating: 3,
    lane: "wholesale",
    priceUsd: 135,
    priceIdr: 0,
    roomType: "family",
    maxOccupancy: 4,
    amenities: ["WiFi", "Breakfast"],
    category: "city-center",
    distanceFromAirportKm: 45,
    slotDuration: "24h",
    supplierName: "Restel",
    wholesalePricing: { supplierBaseAmount: 115, supplierCurrency: "EUR", markupRate: 0.1 },
    createdAt: "2026-01-07",
  },
  {
    id: "15",
    title: "Sydney Airport Rest Zone",
    address: "Mascot, Sydney",
    city: "Sydney",
    country: "Australia",
    image: img("photo-1582719478250-c89cae4dc85b"),
    rating: 4.7,
    starRating: 4,
    lane: "direct",
    priceUsd: 48,
    priceIdr: 760000,
    roomType: "double",
    maxOccupancy: 2,
    amenities: ["WiFi", "AC", "Airport shuttle", "Pool"],
    category: "near-airport",
    distanceFromAirportKm: 2.8,
    slotDuration: "12h",
    ringFencedRooms: 9,
    nextAvailableSlot: "00:00 today",
    createdAt: "2026-01-06",
  },
  {
    id: "16",
    title: "Bangalore Tech Park Hotel",
    address: "Electronic City, Bangalore",
    city: "Bangalore",
    country: "India",
    image: img("photo-1590490360182-c33d57733427"),
    rating: 4.5,
    starRating: 4,
    lane: "wholesale",
    priceUsd: 72,
    priceIdr: 0,
    roomType: "double",
    maxOccupancy: 2,
    amenities: ["WiFi", "AC", "Gym", "Breakfast"],
    category: "business",
    distanceFromAirportKm: 40,
    slotDuration: "24h",
    supplierName: "MakeMyTrip B2B",
    wholesalePricing: { supplierBaseAmount: 62, supplierCurrency: "USD", markupRate: 0.13 },
    createdAt: "2026-01-05",
  },
];

/** Recompute guest USD from supplier quote; attach hotel timezone for slot cutoffs */
export const MOCK_PROPERTIES: Property[] = RAW_PROPERTIES.map((property) => {
  const withTimezone: Property = {
    ...property,
    timezone: getTimezoneForCity(property.city, property.country),
  };

  if (withTimezone.wholesalePricing) {
    return {
      ...withTimezone,
      priceUsd: getWholesaleGuestPriceUsdRounded(withTimezone.wholesalePricing),
    };
  }

  return withTimezone;
});
